package com.octopus.socialnetwork.domain.usecase.authentication.firebase

import android.util.Log
import com.octopus.socialnetwork.data.repository.authentication.AuthenticationRepository
import javax.inject.Inject

class StoreUserTokenUseCase @Inject constructor(
    private val authenticationRepository: AuthenticationRepository,
) {
    suspend operator fun invoke() {
        val fcmToken = authenticationRepository.getFirebaseFcmToken() ?: ""
        Log.i("FCM_TOKEN", "fcm token generated by firebase is $fcmToken")
        if (fcmToken.isNotEmpty()) {
            authenticationRepository.writeFcmToken(fcmToken)
        }
    }
}
